server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fitbyte}
    username: ${SPRING_DATASOURCE_USERNAME:fitbyte}
    password: ${SPRING_DATASOURCE_PASSWORD:fitbyte}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info
